import { IField } from "@/utils/interfaces";

export const fields: IField[] = [
  {
    id: 0,
    name: "start",
    position: "corner",
    color: null,
    type: "start",
  },
  {
    id: 1,
    name: "Konopacka",
    position: "left",
    color: "#451a03",
    price: 60,
    type: "street",
  },
  {
    id: 2,
    name: "Kasa Społeczna",
    position: "left",
    color: null,
    type: "communityChest",
  },
  {
    id: 3,
    name: "Stalowa",
    position: "left",
    color: "#451a03",
    type: "street",
    price: 60,
  },
  {
    id: 4,
    name: "Podatek dochodowy",
    position: "left",
    color: null,
    price: 200,
    type: "tax",
  },
  {
    id: 5,
    name: "Dworzec 1",
    position: "left",
    color: null,
    price: 200,
    type: "station",
  },
  {
    id: 6,
    name: "Radzymińska",
    position: "left",
    color: "#67e8f9",
    price: 100,
    type: "street",
  },
  {
    id: 7,
    name: "Szansa",
    position: "left",
    color: null,
    type: "chance",
  },
  {
    id: 8,
    name: "Jagiellońska",
    position: "left",
    color: "#67e8f9",
    price: 100,
    type: "street",
  },
  {
    id: 9,
    name: "Targowa",
    position: "left",
    color: "#67e8f9",
    price: 120,
    type: "street",
  },
  {
    id: 10,
    name: "Więzienie",
    position: "corner",
    color: null,
    type: "jail",
  },
  {
    id: 39,
    name: "Aleje Ujazdowskie",
    position: "bottom",
    color: "#1e40af",
    price: 400,
    type: "street",
  },
  {
    id: 11,
    name: "Płowiecka",
    position: "top",
    color: "#ec4899",
    price: 140,
    type: "street",
  },
  {
    id: 38,
    name: "Podatek dochodowy",
    position: "bottom",
    color: null,
    price: 100,
    type: "tax",
  },
  {
    id: 12,
    name: "Elektrownia",
    position: "top",
    color: null,
    price: 150,
    type: "industry",
  },
  {
    id: 37,
    name: "Belwederska",
    position: "bottom",
    color: "#1e40af",
    price: 350,
    type: "street",
  },
  {
    id: 13,
    name: "Marsa",
    position: "top",
    color: "#ec4899",
    price: 140,
    type: "street",
  },
  { id: 36, name: "Szansa", position: "bottom", color: null, type: "chance" },
  {
    id: 14,
    name: "Grochowska",
    position: "top",
    color: "#ec4899",
    price: 160,
    type: "street",
  },
  {
    id: 35,
    name: "Dworzec 4",
    position: "bottom",
    color: null,
    price: 200,
    type: "station",
  },
  {
    id: 15,
    name: "Dworzec 2",
    position: "top",
    color: null,
    price: 200,
    type: "station",
  },
  {
    id: 34,
    name: "Aleje Jerozolimskie",
    position: "bottom",
    color: "green",
    price: 320,
    type: "street",
  },
  {
    id: 16,
    name: "Obozowa",
    position: "top",
    color: "#fb923c",
    price: 180,
    type: "street",
  },
  {
    id: 33,
    name: "Kasa społeczna",
    position: "bottom",
    color: null,
    type: "communityChest",
  },
  {
    id: 17,
    name: "Kasa społeczna",
    position: "top",
    color: null,
    type: "communityChest",
  },
  {
    id: 32,
    name: "Marszałkowska",
    position: "bottom",
    color: "green",
    price: 300,
    type: "street",
  },

  {
    id: 18,
    name: "Górczewska",
    position: "top",
    color: "#fb923c",
    price: 180,
    type: "street",
  },

  {
    id: 31,
    name: "Plac trzech krzyży",
    position: "bottom",
    color: "green",
    price: 300,
    type: "street",
  },

  {
    id: 19,
    name: "Wolska",
    position: "top",
    color: "#fb923c",
    price: 200,
    type: "street",
  },
  {
    id: 30,
    name: "Idź do więzienia",
    position: "corner",
    color: null,
    type: "goToJail",
  },
  {
    id: 29,
    name: "Nowy Świat",
    position: "right",
    color: "yellow",
    price: 280,
    type: "street",
  },
  {
    id: 28,
    name: "Wodociągi",
    position: "right",
    color: null,
    price: 150,
    type: "industry",
  },
  {
    id: 27,
    name: "Krakowskie Przedmieście",
    position: "right",
    color: "yellow",
    price: 260,
    type: "street",
  },
  {
    id: 26,
    name: "Świętokrzyska",
    position: "right",
    color: "yellow",
    price: 260,
    type: "street",
  },
  {
    id: 25,
    name: "Dworzec 3",
    position: "right",
    color: null,
    price: 200,
    type: "station",
  },
  {
    id: 24,
    name: "Wilsona",
    position: "right",
    color: "red",
    price: 240,
    type: "street",
  },

  {
    id: 23,
    name: "Słowackiego",
    position: "right",
    color: "red",
    price: 220,
    type: "street",
  },
  { id: 22, name: "Szansa", position: "right", color: null, type: "chance" },
  {
    id: 21,
    name: "Mickiewicza",
    position: "right",
    color: "red",
    price: 220,
    type: "street",
  },

  {
    id: 20,
    name: "Bezpłatny parking",
    position: "corner",
    color: null,
    type: "freeParking",
  },
];

export interface FieldProps {
  field: IField;
}
