import { IField } from "@/utils/interfaces";

export const fields: IField[] = [
  {
    id: 0,
    name: "start",
    position: "corner",
    color: null,
    type: "start",
  },
  {
    id: 1,
    name: "Konopacka",
    position: "left",
    color: "#451a03",
    price: 60,
    type: "street",
    costs: {
      front: {
        tax: 2,
        fullSet: 4,
        withOne: 10,
        withTwo: 30,
        withThree: 90,
        withFour: 160,
        withHotel: 250,
        houseCost: 50,
        hotelCost: 50,
      },
      back: {
        mortgage: 30,
        repayment: 33,
      },
    },
  },
  {
    id: 2,
    name: "Kasa Społeczna",
    position: "left",
    color: null,
    type: "communityChest",
  },
  {
    id: 3,
    name: "Stalowa",
    position: "left",
    color: "#451a03",
    type: "street",
    price: 60,
    costs: {
      front: {
        tax: 4,
        fullSet: 8,
        withOne: 20,
        withTwo: 60,
        withThree: 180,
        withFour: 320,
        withHotel: 450,
        houseCost: 50,
        hotelCost: 50,
      },
      back: {
        mortgage: 30,
        repayment: 33,
      },
    },
  },
  {
    id: 4,
    name: "Podatek dochodowy",
    position: "left",
    color: null,
    price: 200,
    type: "tax",
  },
  {
    id: 5,
    name: "Dworzec 1",
    position: "left",
    color: null,
    price: 200,
    type: "station",
    costs: {
      front: {
        tax: 25,
        taxForTwo: 50,
        taxForThree: 100,
        taxForFour: 200,
      },
      back: {
        mortgage: 100,
        repayment: 110,
      },
    },
  },
  {
    id: 6,
    name: "Radzymińska",
    position: "left",
    color: "#67e8f9",
    price: 100,
    type: "street",
    costs: {
      front: {
        tax: 6,
        fullSet: 12,
        withOne: 30,
        withTwo: 90,
        withThree: 270,
        withFour: 400,
        withHotel: 550,
        houseCost: 50,
        hotelCost: 50,
      },
      back: {
        mortgage: 50,
        repayment: 55,
      },
    },
  },
  {
    id: 7,
    name: "Szansa",
    position: "left",
    color: null,
    type: "chance",
  },
  {
    id: 8,
    name: "Jagiellońska",
    position: "left",
    color: "#67e8f9",
    price: 100,
    type: "street",
    costs: {
      front: {
        tax: 6,
        fullSet: 12,
        withOne: 30,
        withTwo: 90,
        withThree: 270,
        withFour: 400,
        withHotel: 550,
        houseCost: 50,
        hotelCost: 50,
      },
      back: {
        mortgage: 50,
        repayment: 55,
      },
    },
  },
  {
    id: 9,
    name: "Targowa",
    position: "left",
    color: "#67e8f9",
    price: 120,
    type: "street",
    costs: {
      front: {
        tax: 8,
        fullSet: 16,
        withOne: 40,
        withTwo: 100,
        withThree: 300,
        withFour: 450,
        withHotel: 600,
        houseCost: 50,
        hotelCost: 50,
      },
      back: {
        mortgage: 60,
        repayment: 66,
      },
    },
  },
  {
    id: 10,
    name: "Więzienie",
    position: "corner",
    color: null,
    type: "jail",
  },
  {
    id: 39,
    name: "Aleje Ujazdowskie",
    position: "bottom",
    color: "#1e40af",
    price: 400,
    type: "street",
    costs: {
      front: {
        tax: 50,
        fullSet: 100,
        withOne: 200,
        withTwo: 600,
        withThree: 1400,
        withFour: 1700,
        withHotel: 2000,
        houseCost: 200,
        hotelCost: 200,
      },
      back: {
        mortgage: 200,
        repayment: 220,
      },
    },
  },
  {
    id: 11,
    name: "Płowiecka",
    position: "top",
    color: "#ec4899",
    price: 140,
    type: "street",
    costs: {
      front: {
        tax: 10,
        fullSet: 20,
        withOne: 50,
        withTwo: 150,
        withThree: 450,
        withFour: 625,
        withHotel: 750,
        houseCost: 100,
        hotelCost: 100,
      },
      back: {
        mortgage: 70,
        repayment: 77,
      },
    },
  },
  {
    id: 38,
    name: "Podatek dochodowy",
    position: "bottom",
    color: null,
    price: 100,
    type: "tax",
  },
  {
    id: 12,
    name: "Elektrownia",
    position: "top",
    color: null,
    price: 150,
    type: "industry",
    costs: {
      front: {
        tax: 4,
        taxForTwo: 10,
      },
      back: {
        mortgage: 75,
        repayment: 83,
      },
    },
  },
  {
    id: 37,
    name: "Belwederska",
    position: "bottom",
    color: "#1e40af",
    price: 350,
    type: "street",
    costs: {
      front: {
        tax: 35,
        fullSet: 70,
        withOne: 175,
        withTwo: 500,
        withThree: 1100,
        withFour: 1300,
        withHotel: 1500,
        houseCost: 200,
        hotelCost: 200,
      },
      back: {
        mortgage: 175,
        repayment: 193,
      },
    },
  },
  {
    id: 13,
    name: "Marsa",
    position: "top",
    color: "#ec4899",
    price: 140,
    type: "street",
    costs: {
      front: {
        tax: 10,
        fullSet: 20,
        withOne: 50,
        withTwo: 150,
        withThree: 450,
        withFour: 625,
        withHotel: 750,
        houseCost: 100,
        hotelCost: 100,
      },
      back: {
        mortgage: 70,
        repayment: 77,
      },
    },
  },
  { id: 36, name: "Szansa", position: "bottom", color: null, type: "chance" },
  {
    id: 14,
    name: "Grochowska",
    position: "top",
    color: "#ec4899",
    price: 160,
    type: "street",
    costs: {
      front: {
        tax: 12,
        fullSet: 24,
        withOne: 60,
        withTwo: 180,
        withThree: 500,
        withFour: 700,
        withHotel: 900,
        houseCost: 100,
        hotelCost: 100,
      },
      back: {
        mortgage: 80,
        repayment: 88,
      },
    },
  },
  {
    id: 35,
    name: "Dworzec 4",
    position: "bottom",
    color: null,
    price: 200,
    type: "station",
    costs: {
      front: {
        tax: 25,
        taxForTwo: 50,
        taxForThree: 100,
        taxForFour: 200,
      },
      back: {
        mortgage: 100,
        repayment: 110,
      },
    },
  },
  {
    id: 15,
    name: "Dworzec 2",
    position: "top",
    color: null,
    price: 200,
    type: "station",
    costs: {
      front: {
        tax: 25,
        taxForTwo: 50,
        taxForThree: 100,
        taxForFour: 200,
      },
      back: {
        mortgage: 100,
        repayment: 110,
      },
    },
  },
  {
    id: 34,
    name: "Aleje Jerozolimskie",
    position: "bottom",
    color: "green",
    price: 320,
    type: "street",
    costs: {
      front: {
        tax: 28,
        fullSet: 56,
        withOne: 150,
        withTwo: 450,
        withThree: 1000,
        withFour: 1200,
        withHotel: 1400,
        houseCost: 200,
        hotelCost: 200,
      },
      back: {
        mortgage: 160,
        repayment: 176,
      },
    },
  },
  {
    id: 16,
    name: "Obozowa",
    position: "top",
    color: "#fb923c",
    price: 180,
    type: "street",
    costs: {
      front: {
        tax: 14,
        fullSet: 28,
        withOne: 70,
        withTwo: 200,
        withThree: 550,
        withFour: 750,
        withHotel: 950,
        houseCost: 100,
        hotelCost: 100,
      },
      back: {
        mortgage: 90,
        repayment: 99,
      },
    },
  },
  {
    id: 33,
    name: "Kasa społeczna",
    position: "bottom",
    color: null,
    type: "communityChest",
  },
  {
    id: 17,
    name: "Kasa społeczna",
    position: "top",
    color: null,
    type: "communityChest",
  },
  {
    id: 32,
    name: "Marszałkowska",
    position: "bottom",
    color: "green",
    price: 300,
    type: "street",
    costs: {
      front: {
        tax: 26,
        fullSet: 52,
        withOne: 130,
        withTwo: 390,
        withThree: 900,
        withFour: 1100,
        withHotel: 1275,
        houseCost: 200,
        hotelCost: 200,
      },
      back: {
        mortgage: 150,
        repayment: 165,
      },
    },
  },

  {
    id: 18,
    name: "Górczewska",
    position: "top",
    color: "#fb923c",
    price: 180,
    type: "street",
    costs: {
      front: {
        tax: 14,
        fullSet: 28,
        withOne: 70,
        withTwo: 200,
        withThree: 550,
        withFour: 750,
        withHotel: 950,
        houseCost: 100,
        hotelCost: 100,
      },
      back: {
        mortgage: 90,
        repayment: 99,
      },
    },
  },

  {
    id: 31,
    name: "Plac trzech krzyży",
    position: "bottom",
    color: "green",
    price: 300,
    type: "street",
    costs: {
      front: {
        tax: 26,
        fullSet: 52,
        withOne: 130,
        withTwo: 390,
        withThree: 900,
        withFour: 1100,
        withHotel: 1275,
        houseCost: 200,
        hotelCost: 200,
      },
      back: {
        mortgage: 150,
        repayment: 165,
      },
    },
  },

  {
    id: 19,
    name: "Wolska",
    position: "top",
    color: "#fb923c",
    price: 200,
    type: "street",
    costs: {
      front: {
        tax: 16,
        fullSet: 32,
        withOne: 80,
        withTwo: 220,
        withThree: 600,
        withFour: 800,
        withHotel: 1000,
        houseCost: 100,
        hotelCost: 100,
      },
      back: {
        mortgage: 100,
        repayment: 110,
      },
    },
  },
  {
    id: 30,
    name: "Idź do więzienia",
    position: "corner",
    color: null,
    type: "goToJail",
  },
  {
    id: 29,
    name: "Nowy Świat",
    position: "right",
    color: "yellow",
    price: 280,
    type: "street",
    costs: {
      front: {
        tax: 24,
        fullSet: 48,
        withOne: 120,
        withTwo: 360,
        withThree: 850,
        withFour: 1025,
        withHotel: 1200,
        houseCost: 150,
        hotelCost: 150,
      },
      back: {
        mortgage: 140,
        repayment: 154,
      },
    },
  },
  {
    id: 28,
    name: "Wodociągi",
    position: "right",
    color: null,
    price: 150,
    type: "industry",
    costs: {
      front: {
        tax: 4,
        taxForTwo: 10,
      },
      back: {
        mortgage: 75,
        repayment: 83,
      },
    },
  },
  {
    id: 27,
    name: "Krakowskie Przedmieście",
    position: "right",
    color: "yellow",
    price: 260,
    type: "street",
    costs: {
      front: {
        tax: 22,
        fullSet: 44,
        withOne: 110,
        withTwo: 330,
        withThree: 800,
        withFour: 975,
        withHotel: 1150,
        houseCost: 150,
        hotelCost: 150,
      },
      back: {
        mortgage: 130,
        repayment: 143,
      },
    },
  },
  {
    id: 26,
    name: "Świętokrzyska",
    position: "right",
    color: "yellow",
    price: 260,
    type: "street",
    costs: {
      front: {
        tax: 22,
        fullSet: 44,
        withOne: 110,
        withTwo: 330,
        withThree: 800,
        withFour: 975,
        withHotel: 1150,
        houseCost: 150,
        hotelCost: 150,
      },
      back: {
        mortgage: 130,
        repayment: 143,
      },
    },
  },
  {
    id: 25,
    name: "Dworzec 3",
    position: "right",
    color: null,
    price: 200,
    type: "station",
    costs: {
      front: {
        tax: 25,
        taxForTwo: 50,
        taxForThree: 100,
        taxForFour: 200,
      },
      back: {
        mortgage: 100,
        repayment: 110,
      },
    },
  },
  {
    id: 24,
    name: "Wilsona",
    position: "right",
    color: "red",
    price: 240,
    type: "street",
    costs: {
      front: {
        tax: 20,
        fullSet: 40,
        withOne: 100,
        withTwo: 300,
        withThree: 750,
        withFour: 925,
        withHotel: 1100,
        houseCost: 150,
        hotelCost: 150,
      },
      back: {
        mortgage: 120,
        repayment: 132,
      },
    },
  },

  {
    id: 23,
    name: "Słowackiego",
    position: "right",
    color: "red",
    price: 220,
    type: "street",
    costs: {
      front: {
        tax: 18,
        fullSet: 36,
        withOne: 90,
        withTwo: 250,
        withThree: 700,
        withFour: 875,
        withHotel: 1050,
        houseCost: 150,
        hotelCost: 150,
      },
      back: {
        mortgage: 110,
        repayment: 121,
      },
    },
  },
  { id: 22, name: "Szansa", position: "right", color: null, type: "chance" },
  {
    id: 21,
    name: "Mickiewicza",
    position: "right",
    color: "red",
    price: 220,
    type: "street",
    costs: {
      front: {
        tax: 18,
        fullSet: 36,
        withOne: 90,
        withTwo: 250,
        withThree: 700,
        withFour: 875,
        withHotel: 1050,
        houseCost: 150,
        hotelCost: 150,
      },
      back: {
        mortgage: 110,
        repayment: 121,
      },
    },
  },

  {
    id: 20,
    name: "Bezpłatny parking",
    position: "corner",
    color: null,
    type: "freeParking",
  },
];

export interface FieldProps {
  field: IField;
}
